### ISSUE TITLE
'xrange()' is not defined

### ISSUE THREAD

**Issue by johnwarh** [delimitry/octree_color_quantizer#1]
When trying to run the code, I get the following error message:

"PS D:\Users\John\Documents\GitHub\octree_color_quantizer> python main.py
Traceback (most recent call last):
  File "D:\Users\John\Documents\GitHub\octree_color_quantizer\main.py", line 43, in <module>
    main()
  File "D:\Users\John\Documents\GitHub\octree_color_quantizer\main.py", line 14, in main
    octree = OctreeQuantizer()
             ^^^^^^^^^^^^^^^^^
  File "D:\Users\John\Documents\GitHub\octree_color_quantizer\octree_quantizer.py", line 138, in __init__
    self.levels = {i: [] for i in xrange(OctreeQuantizer.MAX_DEPTH)}
                                  ^^^^^^
NameError: name 'xrange' is not defined. Did you mean: 'range'?"

Is there a input argument that defines this object, that I'm missing?

**Comment by delimitry** [comment]
Hi @johnwarh, yes you can use range instead of xrange. 
I wrote this code for Python 2.7.

**Comment by johnwarh** [comment]
I just figured that out myself after looking at the fork in the repository.  Thank you for your quick response.
